### ISSUE TITLE
1.19.2 - subpocket fails to load correctly

### ISSUE THREAD

**Issue by LLEE003377** [necauqua/subpocket#6]
i get this message upon starting the game

subpocket (subpocket) has failed to load correctly
java.lang.noclassdeffounderror:
net/minecraftforge/event/creativemodetabevent$buildcontents

**Comment by necauqua** [comment]
hmm, it seems that forge follows mojangs policy of 'lets make 1.19.3 totally incompatible with 1.19.2', ughh

The current version of subpocket only works with 1.19.3 it seems, maybe I'll fix that somehow

**Comment by Minebrah** [comment]
Same:

Mod File: /C:/Users/world/AppData/Roaming/.minecraft/mods/subpocket-1.19-9.0.0.0.jar
	Failure message: subpocket (subpocket) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/CreativeModeTabEvent$BuildContents
	Mod Version: 1.19-9.0.0.0
	Mod Issue URL: https://github.com/necauqua/subpocket/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.CreativeModeTabEvent$BuildContents

**Comment by necauqua** [comment]
I've released ([md](https://modrinth.com/mod/subpocket/version/1.19.2-10.0.0.0)/[cf](https://legacy.curseforge.com/minecraft/mc-mods/subpocket/files/4555480)/[gh](https://github.com/necauqua/subpocket/releases/tag/v1.19.2-10.0.0.0)) a separate 1.19.2-specific version which has this fixed
